### ISSUE TITLE
(OS/X 10.10) Running Breach From CLI: apiDispatcher not defined

### ISSUE THREAD

**Issue by derekbrown** [spolu/breach_core#141]
On OS/X 10.10, I'm trying to get to the bottom of some of the other issues. In trying to run the app manually using `node index.js`, I receive the following error:

`````` Repos/breach_core/node_modules/exo_browser/lib/api.js:22
var _exo_browser = apiDispatcher.requireExoBrowser();
                   ^
ReferenceError: apiDispatcher is not defined
    at Object.<anonymous> (/Repos/breach_core/node_modules/exo_browser/lib/api.js:22:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Repos/breach_core/lib/auto_updater.js:17:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)```

Suggestions?
``````

**Comment by ghost** [comment]
I am getting this same error, npm install does not fix the issue.

**Comment by spolu** [comment]
apiDispatcher is exposed through native bindings in the nodeJS flavor embeded in Breach's executable, so you can't run the whole thing from node directly unfortunately

**Comment by derekbrown** [comment]
So what is the proper way of running one's local instance of Breach?

**Comment by spolu** [comment]
Using the ExoBrowser. See: https://github.com/breach/breach_core/wiki/Building-Breach-from-Source
