### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by naknut** [spolu/breach_core#156]
I have tried to build and run Breach my self but i cant get it to work. I guessed i should use
    make install
and then run the index.js but it doesnt seem to work. I get the following error:
    [2014-07-19T07:01:15.063Z] [index] Breach v0.3.21-alpha.5 Starting...

```
/Users/Naknut/Development/breach_core/node_modules/exo_browser/lib/api.js:22
var _exo_browser = apiDispatcher.requireExoBrowser();
               ^
ReferenceError: apiDispatcher is not defined
    at Object.<anonymous>     (/Users/Naknut/Development/breach_core/node_modules/exo_browser/lib/api.js:22:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous>     (/Users/Naknut/Development/breach_core/lib/auto_updater.js:17:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Some instructions on how to build and run from source would help.

**Comment by fenduru** [comment]
https://github.com/breach/breach_core/wiki/Building-Breach-from-Source
