### ISSUE TITLE
How does it work ?

### ISSUE THREAD

**Issue by amaurybrisou** [spolu/breach_core#55]
Hi everyone,

I'm experiencing a problem during the really beginning of the compilation.
First I clone 'breach_core', then make 'dist_darwin'. During the execution, it doesn't find exo_browser archive. 'tar' command exit with an error code. I searched a little but there apparently no archive at all, anywhere in tmp or pwd.

here is what I have :

```
[... npm install logs ...]
node dist/darwin.js "x64" "__DUMMY__"
[2014-07-05T09:25:48.278Z] Making `darwin` distribution for v0.3.10-alpha.2
[2014-07-05T09:25:48.279Z] Using breach_core: /home/erol/breach/package
[2014-07-05T09:25:48.279Z] Using arch: x64
[2014-07-05T09:25:48.279Z] Using ExoBrowser: __DUMMY__
stderr: tar (child): __DUMMY__: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now

stderr: tar: Child returned status 2
tar: Error is not recoverable: exiting now

[2014-07-05T09:25:48.294Z] *********************************************
[2014-07-05T09:25:48.294Z] ERROR: Extraction failed with code: 2
[2014-07-05T09:25:48.294Z] *********************************************
[2014-07-05T09:25:48.297Z] auto_updater:failed_extraction: Extraction failed with code: 2
[2014-07-05T09:25:48.297Z]     at Object.exports.err (/home/erol/breach/package/lib/common.js:309:13)
[2014-07-05T09:25:48.297Z]     at ChildProcess.<anonymous> (/home/erol/breach/package/dist/darwin.js:69:27)
[2014-07-05T09:25:48.297Z]     at ChildProcess.EventEmitter.emit (events.js:98:17)
[2014-07-05T09:25:48.297Z]     at maybeClose (child_process.js:743:16)
[2014-07-05T09:25:48.297Z]     at Socket.<anonymous> (child_process.js:956:11)
[2014-07-05T09:25:48.297Z]     at Socket.EventEmitter.emit (events.js:95:17)
[2014-07-05T09:25:48.297Z]     at Pipe.close (net.js:466:12)
[2014-07-05T09:25:48.297Z] ---------------------------------------------
make: *** [dist_darwin] Error 1
```

I'd really like to compile it, thanks in advance.

Amaury

**Comment by spolu** [comment]
Hi Amaury, to produce a distribution version of Breach you indeed need the ExoBrowser binaries available.

Breach is coded in JavaScript but need te ExoBrowser to be executed (chromium content module + nodeJs to simplify)

You can go ahead and build the ExoBrowser yourself with the instruction here: https://github.com/breach/exo_browser/wiki/Building-the-ExoBrowser

Or if you want to save some time before going through an entire compilation, you can download a fairly recent build of Breach on our mailing list: 
https://groups.google.com/forum/m/#!forum/breach-dev

We'll be realeasing the latest alpha more broadly to the public this week (hopefully)!

Let us know if you have any issue or question!
