### ISSUE TITLE
Crashes on start up (OS X 10.7.5)

### ISSUE THREAD

**Issue by jackjennings** [spolu/breach_core#59]
```
7/10/14 12:12:29.885 PM [0x0-0x178178].org.breach.Breach: [48168:20999:0710/121229:60046176394503:WARNING:dns_config_service_posix.cc(151)] dns_config has unhandled options!
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach: [2014-07-10T19:12:29.934Z] [index] Breach v0.3.20-alpha.5 Starting...
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach: module.js:333
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     throw err;
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:           ^
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach: Error: Cannot find module 'request'
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     at Function.Module._resolveFilename (module.js:331:15)
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     at Function.Module._load (module.js:273:25)
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     at Module.require (module.js:357:17)
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     at require (module.js:373:17)
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     at Object.<anonymous> (/Users/jackjennings/Desktop/Breach.app/Contents/Resources/shell/lib/auto_updater.js:18:15)
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     at Module._compile (module.js:449:26)
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     at Object.Module._extensions..js (module.js:467:10)
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     at Module.load (module.js:349:32)
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     at Function.Module._load (module.js:305:12)
7/10/14 12:12:30.012 PM [0x0-0x178178].org.breach.Breach:     at Module.require (module.js:357:17)
```

**Comment by jackjennings** [comment]
Hopefully this is the correct repo for this?

**Comment by spolu** [comment]
Yep totally.

Basically the npm install didnt go well. You can remove `~/.breach` or `~/Library/Application Support/breach` and relaunch breach... this may fix the issue

**Comment by spolu** [comment]
See: https://github.com/breach/breach_core/issues/58

**Comment by jackjennings** [comment]
Unfortunately I don't have either of those folders…

```
$ ls -al ~ | grep .breach

$ ls -al ~/Library/Application\ Support/ | grep breach

```

**Comment by spolu** [comment]
And what happens when you attempt to rerun Breach

**Comment by jackjennings** [comment]
The same error message is thrown each time, without creating either the aforementioned folders.

**Comment by spolu** [comment]
I'm wondering if this is related to the fact that you're 10.7...

**Comment by jackjennings** [comment]
Perhaps… I know I'm a bit behind the times at this point.

**Comment by spolu** [comment]
:)

**Comment by spolu** [comment]
No plan to support 10.7 right now
