### ISSUE TITLE
Doesn't start on OS X

### ISSUE THREAD

**Issue by herrernst** [spolu/breach_core#93]
I've downloaded and extracted breach-v0.3.20-alpha.5-darwin-ia32.tar.gz, after opening I'm prompted to install mod_strip, but then it crashes. If I start via CLI, I get this:

```
breach-v0.3.20-alpha.5-darwin-ia32/Breach.app/Contents/MacOS/Breach 
[2014-07-11T09:18:45.659Z] [index] Breach v0.3.20-alpha.5 Starting...
[2014-07-11T09:18:46.395Z] [core_ui] HTTP Server started on `http://127.0.0.1:58441/`
[22914:1287:0711/111846:91408326746042:INFO:exo_session.cc(88)] VisitedLink Init: 1
[22914:1287:0711/111846:91408326809474:INFO:devtools_delegate.cc(132)] ExoBrowserDevToolsDelegate Constructor
[22914:1287:0711/111846:91408326839218:INFO:content_browser_client.cc(190)] Register Session
[22914:25863:0711/111846:91408403737223:INFO:exo_browser_wrap.cc(331)] ExoBrowserWrap CreateCallback
[22914:25863:0711/111846:91408404168571:INFO:exo_session_wrap.cc(268)] CreateCallback ExoSessionWrap
[22914:1287:0711/111846:91408408913600:INFO:exo_frame.cc(78)] ExoFrame Constructor (web_contents created) [0x79103000]
[22914:25863:0711/111846:91408413588607:INFO:exo_frame_wrap.cc(322)] CreateCallback ExoFrameWrap
[22914:1287:0711/111846:91408414514559:INFO:exo_frame.cc(106)] ExoFrame SetType [0x78e80fd0]: 2
[22914:1287:0711/111846:91408414547643:INFO:exo_frame.cc(97)] ExoFrame SetParent [0x79103000]: 0x79a35340
[2014-07-11T09:18:46.633Z] [index] Startup Complete
[22914:27911:0711/111846:91408547934021:INFO:exo_session_cookie_store.cc(31)] Load
[22914:27911:0711/111846:91408547998498:INFO:exo_session_cookie_store.cc(46)] LoadCookiesForKey: ''
[22914:25863:0711/111846:91408548059695:INFO:exo_session_wrap.cc(679)] CookiesLoad [0]
[2014-07-11T09:18:46.644Z] [core_cookies] load_for_key: null
[22914:25863:0711/111846:91408549058538:INFO:exo_session_wrap.cc(646)] CookiesLoadForKey:  [1]
[2014-07-11T09:18:46.645Z] [core_cookies] load_for_key: 
[2014-07-11T09:18:46.646Z] [core_cookies] loaded 0 cookies
[22914:25863:0711/111846:91408550197830:INFO:exo_session_wrap.cc(606)] CookiesLoadForKeyCallback [0]
[22914:25863:0711/111846:91408550217331:INFO:exo_session_wrap.cc(620)] RETURNED: 0
[2014-07-11T09:18:46.647Z] [core_cookies] loaded 0 cookies
[22914:25863:0711/111846:91408550733087:INFO:exo_session_wrap.cc(606)] CookiesLoadForKeyCallback [1]
[22914:25863:0711/111846:91408550751210:INFO:exo_session_wrap.cc(620)] RETURNED: 0
[2014-07-11T09:18:47.032Z] [auto_updater] Breach v0.3.20-alpha.5 is up to date!
[2014-07-11T09:18:47.074Z] [core_ui] HANDSHAKE: splash
[2014-07-11T09:18:47.080Z] [core_ui] HANDSHAKE: modules
[2014-07-11T09:18:47.103Z] [core_ui] HANDSHAKE: modules
npm WARN package.json mod_stats@0.1.4-alpha.5 No description
npm WARN package.json mod_stats@0.1.4-alpha.5 No repository field.
npm WARN package.json mod_stats@0.1.4-alpha.5 No README data
[2014-07-11T09:18:55.199Z] *********************************************
[2014-07-11T09:18:55.199Z] ERROR: Request path contains unescaped characters.
[2014-07-11T09:18:55.199Z] *********************************************
[2014-07-11T09:18:55.201Z] TypeError: Request path contains unescaped characters.
[2014-07-11T09:18:55.201Z]     at new ClientRequest (_http_client.js:73:11)
[2014-07-11T09:18:55.201Z]     at TunnelingAgent.exports.request (http.js:52:10)
[2014-07-11T09:18:55.201Z]     at TunnelingAgent.createSocket (/Users/username/Downloads/breach-v0.3.20-alpha.5-darwin-ia32/Breach.app/Contents/Resources/shell/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
[2014-07-11T09:18:55.201Z]     at TunnelingAgent.createSecureSocket [as createSocket] (/Users/username/Downloads/breach-v0.3.20-alpha.5-darwin-ia32/Breach.app/Contents/Resources/shell/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
[2014-07-11T09:18:55.201Z]     at TunnelingAgent.addRequest (/Users/username/Downloads/breach-v0.3.20-alpha.5-darwin-ia32/Breach.app/Contents/Resources/shell/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
[2014-07-11T09:18:55.201Z]     at new ClientRequest (_http_client.js:153:16)
[2014-07-11T09:18:55.201Z]     at Object.exports.request (http.js:52:10)
[2014-07-11T09:18:55.201Z]     at Object.exports.request (https.js:136:15)
[2014-07-11T09:18:55.201Z]     at Request.start (/Users/username/Downloads/breach-v0.3.20-alpha.5-darwin-ia32/Breach.app/Contents/Resources/shell/node_modules/npm/node_modules/request/request.js:583:30)
[2014-07-11T09:18:55.201Z]     at Request.end (/Users/username/Downloads/breach-v0.3.20-alpha.5-darwin-ia32/Breach.app/Contents/Resources/shell/node_modules/npm/node_modules/request/request.js:1237:28)
[2014-07-11T09:18:55.201Z] ---------------------------------------------
```

**Comment by nicoleglynn** [comment]
I'm encountering almost the same issue. The app doesn't crash, but mod-strip just never runs. After the onboarding process, I get to what I guess is the module management screen, and mod_strip is listed as stopped. I can click 'run' an it will saying it's running, but it won't stay running. This is on OSX 10.8.2

**Comment by nicoleglynn** [comment]
@herrernst  – I was able to get it running by removing and re-installing mod_strip.

**Comment by jonschwartz** [comment]
On mine, I never got to the onboarding process.  It just opens and nothing shows on the screen.  OSX 10.6.8

**Comment by jonaldomo** [comment]
I am on OSX and mod_strip did not work properly for me after I installed it through the onboarding process.  I had to remove it.  And then add it though the install input at the configure screen.  

I would recommend a text placeholder on the install input bar for the proper wording for a mod.  Or maybe a shorthand, ie mod_strip would translate to github:breach/mod_strip.

**Comment by lazaruslarue** [comment]
On a fairly fresh install of OSX 10.9.4. Everything worked fine for me out of the box.

**Comment by jesusr** [comment]
I am on OSX 10.9.4:
- Install and open Breach;
- Breach ask me to install mod_strip;
- Once installed, i was trying to run but its not responding.
- Manually download the mod_strip module and place it right.
- But... again, mod_strip doesn't run, respond, or anything.

Ideas?

**Comment by spolu** [comment]
There probably was an error while npm installing mod_strip.
Remove `~/Library/Application Support/breach` and restart!

**Comment by herrernst** [comment]
Doesn't solve anything for me, still the same as in the original post. How would I install mod_strip manually?

**Comment by spolu** [comment]
You unfortunately cannot. Can you have a look at the content of `~/Library/Application Support/breach/modules` after running the onboaridng?

**Comment by herrernst** [comment]
List of files:

```
Library/Application Support/breach/modules
Library/Application Support/breach/modules/breach
Library/Application Support/breach/modules/breach/mod_stats#v0.1.4-alpha.5
Library/Application Support/breach/modules/breach/mod_stats#v0.1.4-alpha.5/.gitignore
Library/Application Support/breach/modules/breach/mod_stats#v0.1.4-alpha.5/index.js
Library/Application Support/breach/modules/breach/mod_stats#v0.1.4-alpha.5/lib
Library/Application Support/breach/modules/breach/mod_stats#v0.1.4-alpha.5/lib/common.js
Library/Application Support/breach/modules/breach/mod_stats#v0.1.4-alpha.5/lib/ga.js
Library/Application Support/breach/modules/breach/mod_stats#v0.1.4-alpha.5/lib/stats.js
Library/Application Support/breach/modules/breach/mod_stats#v0.1.4-alpha.5/package.json
Library/Application Support/breach/modules/breach/mod_strip#v0.2.12
Library/Application Support/breach/modules/breach/mod_strip#v0.2.12/.gitignore
Library/Application Support/breach/modules/breach/mod_strip#v0.2.12/controls
Library/Application Support/breach/modules/breach/mod_strip#v0.2.12/controls/assets
Library/Application Support/breach/modules/breach/mod_strip#v0.2.12/controls/assets/fonts
Library/Application Support/breach/modules/breach/mod_strip#v0.2.12/controls/assets/fonts/Roboto-Black.ttf
Library/Application Support/breach/modules/breach/mod_strip#v0.2.12/NOTES
Library/Application Support/breach/modules/extract
Library/Application Support/breach/modules/extract/npm_cache
```

**Comment by spolu** [comment]
It looks like `npm install` did not run.

**Comment by herrernst** [comment]
Okay, I found the source of the problem: I had an https proxy in my .npmrc, and your bundled version of npm seems to have a bug with it, sounds like this: https://github.com/mikeal/request/issues/779

**Comment by spolu** [comment]
Yep that's probably it! Thanks for the report. This should be fixed by next version of Breach.
